### ISSUE TITLE
[Feat]: Allow support for harness.io/pipelines annotations without the keys

### ISSUE THREAD

**Issue by OrkoHunter** [harness/backstage-plugins#130]
## 🔖 Feature description

Currently the `harness.io/pipelines` annotations expects an array of key value pairs like this

```
metadata:
  annotations:
    harness.io/pipelines: |
      ci: ci_pipeline_link
      cd: cd_pipeline_link
      key1: url1
```

However it should also be possible to skip these keys here. If the keys are missing, then the pipeline name can be used as the keys in the dropdown list.

```
metadata:
  annotations:
    harness.io/pipelines: |
      ci_pipeline_link
      cd_pipeline_link
      url1
```

or simply

```
metadata:
  annotations:
    harness.io/pipelines: pipeline_link
```

## ✌️ Possible Implementation

https://github.com/harness/backstage-plugins/blob/32d285fedc7d4f8203d0cf69eb3eafffd71d6033/plugins/harness-ci-cd/src/components/ExecutionList/ExecutionList.tsx#L291-L296
