### ISSUE TITLE
[Bug]: harness-ci-cd Plugin only supports URLs from the v1 NG Harness UI

### ISSUE THREAD

**Issue by Jimcumming** [harness/backstage-plugins#140]
## Expected Behavior
Adding a pipeline annotation captured from the new UI should display the pipeline details when viewing the plugin

## Actual behavior
If using new format URL get the following error
```
Error
TypeError

Message
Cannot read properties of undefined (reading 'orgId')
```

## Context
New format URLs have this format
```
https://app.harness.io/ng/account/accountID/module/ci/orgs/orgID/projects/projectID/pipelines/pipelineID/pipeline-studio
```
Older format URLs have this format
```
https://app.harness.io/ng/account/accountID/home/orgs/orgID/projects/projectID/pipelines/pipelineID/pipeline-studio/
```
The /home path has become /module/ci

A similar issue also affects the links to services

## Possible Implementation
Support both formats of URL

## Environment details
harness-ci-cd plugin version 0.10.0
Backstage version 1.28.4

**Comment by OrkoHunter** [comment]
@deba-harness @jenil-harness please take a look.

**Comment by Debanitrkl** [comment]
We do support both the formats in CI/CD plugin, https://github.com/harness/backstage-plugins/blob/de7ff8c92d39f929f9d14016fc68d4318cb80990/plugins/harness-ci-cd/src/hooks/useProjectSlugEntity.tsx#L25-L67

**Comment by Debanitrkl** [comment]
Also could you please share the exact annotation you have used or the `catalog-info.yaml` file.

**Comment by Jimcumming** [comment]
Sure, here is our catalog-info.yaml. 

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-env-s3
  description: A Terraform project for managing S3 buckets. 
  links:
    - url: https://github.com/tractableai/tf-env-s3
      title: Codebase
  annotations:
    github.com/project-slug: tractableai/tf-env-s3
    jira/project-key: INFRA
    harness.io/orgid: Tractable_ENG
    harness.io/pipelines: |
      tf-env-s3: https://app.harness.io/ng/account/oXvBcrhMQiyEPrn2pi0nHQ/home/orgs/Tractable_ENG/projects/infra/pipelines/tfenvs3/pipeline-studio/?storeType=REMOTE&connectorRef=account.Github_via_SSH_ECDSA_key&repoName=tf-env-s3&branch=main
    harness.io/services: |
      tf-env-s3: https://app.harness.io/ng/account/oXvBcrhMQiyEPrn2pi0nHQ/home/orgs/Tractable_ENG/projects/infra/services/tfenvs3?tab=summaryTab
  tags:
    - terraform
    - aws
    - s3
spec:
  type: infrastructure-as-code
  lifecycle: production
  owner: infrastructure-and-security
---
```
