### ISSUE TITLE
[Bug]: CI/CD tab fails to render page, throwing React error in router

### ISSUE THREAD

**Issue by tknguyen3** [harness/backstage-plugins#156]
## Expected Behavior
CI/CD tab should render details

## Actual behavior
Looks like a React error in the router

## Context
Seeing this error when trying to view CI/CD details for an app that we've enabled for this plugin:
```
Error
    at L (https://platform-backstage.<internal-domain>/static/module-react-router.f2b8a208.js:10:2361)
    at sr (https://platform-backstage.<internal-domain>/static/module-react-router.f2b8a208.js:20:2320)
    at En (https://platform-backstage.<internal-domain>/static/module-react-router.f2b8a208.js:20:2285)
    at An (https://platform-backstage.<internal-domain>/static/module-react-router.f2b8a208.js:20:11811)
    at Ci (https://platform-backstage.<internal-domain>/static/module-react-dom.a3000642.js:14:19467)
    at ta (https://platform-backstage.<internal-domain>/static/module-react-dom.a3000642.js:16:43662)
    at qs (https://platform-backstage.<internal-domain>/static/module-react-dom.a3000642.js:16:39462)
    at Jc (https://platform-backstage.<internal-domain>/static/module-react-dom.a3000642.js:16:39393)
    at Hr (https://platform-backstage.<internal-domain>/static/module-react-dom.a3000642.js:16:39252)
    at Yi (https://platform-backstage.<internal-domain>/static/module-react-dom.a3000642.js:16:35674)
```

I've verified the API token has appropriate privileges, though we do enable read-only, anonymous Guest access for our Backstage implementation. There doesn't appear to be any stacktraces in container logs either.

Here are some snippets of the code/configuration:

app-config.production.yaml:
```
proxy:
  endpoints:
    '/harness/prod':
      target: 'https://app.harness.io/'
      headers:
        'x-api-key': ${HARNESS_TOKEN}
```

EntityPage.tsx:
```
import {
  isHarnessCiCdAvailable,
  EntityHarnessCiCdContent,
} from '@harnessio/backstage-plugin-ci-cd';
...
    <EntityLayout.Route
      path="/harness-ci-cd"
      title="Harness CI/CD"
      if={isHarnessCiCdAvailable}
    >
      <EntityHarnessCiCdContent />
    </EntityLayout.Route>

```
![image](https://github.com/user-attachments/assets/bfdc1a59-a219-4ad4-8954-1a08006b6ae9)

## Possible Implementation
Snippet of a test app's `catalog-info.yaml` (I've tried `catalog-info.yaml` with both pipelines and services, and each on its own).
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    harness.io/pipelines: |
      nonprod-deploy: https://app.harness.io/ng/account/<account_id>/module/cd/orgs/default/projects/<project_id>/pipelines/nonproddeploy/pipeline-studio?storeType=INLINE
      prod-deploy: https://app.harness.io/ng/account/<account_id>/module/cd/orgs/default/projects/<project_id>/pipelines/proddeploy/pipeline-studio?storeType=INLINE
    harness.io/services: |
      hellogo: https://app.harness.io/ng/account/<account_id>/module/cd/orgs/default/projects/<project_id>/services/hellogo?tab=configuration
```

## Environment details
Backstage version: `1.33.5`
Plugin version: `^0.11.0`
