### ISSUE TITLE
[Feat]: Add support for multiple projects across orgs

### ISSUE THREAD

**Issue by OrkoHunter** [harness/backstage-plugins#90]
## Need

As of now, the plugin allows to connect a software component with a Harness project. The plugin's annotation configuration then allows to filter based on pipeline IDs and service IDs. However, we've found customers who use different projects for a single service to separate our Development and Production pipelines for example. Some have different projects for CI and CD pipelines.

So, the need is to connect a single software component in Backstage to multiple Pipelines in different projects.

## Proposed solution

We would like to make the annotation very explicit for a software component - give a list of pipelines that you would like to show on the executions page. However, since the Backstage annotations only allow strings, doesn't allow an array or a key-value pair, we'll have to take this up on the UI.

The plugin's proposed solution will have **no annotation requirement** and can be configured on the UI itself.

The first time someone opens the plugin page for a software component

<img width="1228" alt="Screenshot 2023-06-19 at 1 24 08 PM" src="https://github.com/harness/backstage-plugins/assets/8065913/db628890-3f79-46a3-ade9-0f272dde83af">

In the backend counter-part of the plugin, we will store the status of configuration. In the setup, the user can add a label and a url to a pipeline in any project/org of their Harness account.

<img width="989" alt="Screenshot 2023-06-19 at 1 24 16 PM" src="https://github.com/harness/backstage-plugins/assets/8065913/d7ba8512-a61d-4422-a2d6-88e74cdac113">

Once configured, user can see pipeline executions from all of the added pipelines or filter by pipelines.

<img width="978" alt="Screenshot 2023-06-19 at 1 24 20 PM" src="https://github.com/harness/backstage-plugins/assets/8065913/7f44b5d2-c1c6-483f-9fd4-fda2f9631e84">

They will also have the option to add or remove pipelines for a component.

<img width="962" alt="Screenshot 2023-06-19 at 1 24 27 PM" src="https://github.com/harness/backstage-plugins/assets/8065913/e6ab6f33-62b5-4979-8d7f-7548e100edac">

**Permissions:** The actions to setup the plugin and update configurations can use `catalog.entity.update` permission. So, if the user has the permission to update the entity, they should be able to perform the task.

**Comment by OrkoHunter** [comment]
While the UI is great, having the list of pipelines inside the `catalog-info.yaml` makes it declarative and re-usable. We could achieve this either by making the annotation a string of multiple lines.

```
metadata:
  annotations:
    harness.io/pipelines: |
      label1: url1
      label2: url2
      label3: url3
    harness.io/serviceId: |
      label1: serviceA
```

Or by creating a new `metadata` field itself.

```
metadata:
  harness.io/pipelines:
    - label1: url1
    - label2: url2
    - label3: url3
  harness.io/serviceId:
    - label1: serviceA
```


Note: We should think about how to take service IDs as filters for each/every pipeline.
