### ISSUE TITLE
[Bug]: proxy error [HPM] Error occurred while proxying request

### ISSUE THREAD

**Issue by naresh1919** [harness/backstage-plugins#91]
## Expected Behavior

i have added the harness project url in 
harness.io/project-url: https://app.harness.io/ng/account/XXXXXXXX/home/orgs/XXXXX/projects/XXXXXXXX/
spec: its not working and not able to pull the pipeline details into backstage dashboard 
## Actual behavior

Its showing the msg in ci/cd pannel and getting like 
"Harness CI-CD pipelines
Could not find the pipeline executions, please check your configurations in catalog-info.yaml or check your permissions." 
msg in  dashbord.

In server logs: 
"POST /api/proxy/harness/prod/gateway/pipeline/api/pipelines/execution/v2/summary?accountIdentifier=XXXXXXX&routingId=XXXXXXX&orgIdentifier=XXXXXX&projectIdentifier=XXXXX&size=5&page=0 HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" type=incomingRequest
"POST /api/proxy/harness/prod/gateway/pipeline/api/pipelines/execution/v2/summary?accountIdentifier=XXXXXXX&routingId=XXXXXX&orgIdentifier=XXXXXX&projectIdentifier=XXXXXX&size=5&page=0 HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" type=incomingRequest
"GET /api/proxy/harness/prod/gateway/ng/api/licenses/account?routingId=XXXXXX&accountIdentifier=XXXXX HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" type=incomingRequest

proxy error [HPM] Error occurred while proxying request <my ip>:7007/prod/gateway/ng/api/licenses/account?routingId=XXXXXX&accountIdentifier=XXXXX to https://app.harness.io/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors) type=plugin
## Environment details

my config in app-config.yaml
```
proxy:
  '/harness':
      target: 'https://app.harness.io/'
      headers:
        'x-api-key': <my PAT token>
```

**Comment by jenil-harness** [comment]
Hey @naresh1919 
Please use the following config. We will update the documentation.

```
proxy:
  '/harness/prod':
      target: 'https://app.harness.io/'
      headers:
        'x-api-key': <my PAT token>
```
